sudo: required
#jdk: openjdk8

language: android


android:
  components:
  - build-tools-23.0.1
  - android-23

  licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'


before_install:
  - sudo apt -qq update > /dev/null
  - sudo apt -qq install --no-install-recommends build-essential ccache git zlib1g-dev python2.7 python2.7-dev libncurses5:i386 libstdc++6:i386 zlib1g:i386 openjdk-8-jdk unzip ant ccache autoconf libtool > /dev/null
  - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
  - unzip -qq android-ndk-r16b-linux-x86_64.zip -d $HOME
  - export ANDROID_NDK_HOME=$HOME/android-ndk-r16b
  - echo "ANDROID_NDK_HOME" $ANDROID_NDK_HOME
  - export PATH=$PATH:$ANDROID_NDK_HOME
  - export PIP_DISABLE_PIP_VERSION_CHECK=1
  - virtualenv --python=/usr/bin/python2.7 venv/bin/activate
  - pip install --quiet --user -r requirements.txt


install:
  - git clone --depth=50 --branch=master https://github.com/Redwid/youtube-dl.git ../youtube-dl


env:
  global:
    - ANDROID_SDK_HOME=/opt/android/android-sdk


script:
  - sh clean-build-copy.sh

