sudo: required


language: android


android:
  components:
  # Uncomment the lines below if you want to
  # use the latest revision of Android SDK Tools
  # - tools
  # - platform-tools

  # The BuildTools version used by your project
  - build-tools-28.0.3

  # The SDK version used to compile your project
  - android-23

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository

  # Specify at least one system image,
  # if you need to run emulator(s) during your tests
  # - sys-img-x86-android-26
  # - sys-img-armeabi-v7a-android-17

  licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'


before_install:
  - sudo apt update -qq
  - sudo apt install -qq --no-install-recommends python2.7 python3
  - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
  - unzip -qq android-ndk-r16b-linux-x86_64.zip
  - export PIP_DISABLE_PIP_VERSION_CHECK=1
  - virtualenv --python=/usr/bin/python2.7 venv/bin/activate
  - pip install --user -r requirements.txt


env:
  global:
    - ANDROID_SDK_HOME=/opt/android/android-sdk
    - ANDROID_NDK_HOME=`pwd`/android-ndk-r16b


script:
  - sh clean-build-copy.sh
