sudo: required

language: generic

services:
  - docker

before_install:
  - sudo apt update -qq
  - sudo apt install -qq --no-install-recommends python2.7 python3

env:
  global:
    - ANDROID_SDK_HOME=/opt/android/android-sdk
    - ANDROID_NDK_HOME=/opt/android/android-ndk

script:
  - docker sh clean-build-copy.sh
