sudo: required

language: generic

before_install:
  - sudo apt update -qq
  - sudo apt install -qq --no-install-recommends python2.7 python3
  - wget https://dl.google.com/android/repository/android-ndk-r16b-linux-x86_64.zip
  - unzip -qq android-ndk-r16b-linux-x86_64.zip


env:
  global:
    - ANDROID_SDK_HOME=/opt/android/android-sdk
    - ANDROID_NDK_HOME=`pwd`/android-ndk-r16b

script:
  - sh clean-build-copy.sh
